version: '3'

services:
  web:
    build: ./
    restart: always
    volumes:
      - ./:/opt/face-detection
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    build:
      context: ./compose-db
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=demo
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis
    restart: always
  chrome:
    image: robcherry/docker-chromedriver
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "9515"
    ports:
      - 9515:9515
    cap_add:
      - "SYS_ADMIN"

volumes:
  web-data:
  db-data:
